HOST_ETHERNET_INTERFACE=eno1
HOST_TAP_INTERFACE=tap0
sudo iptables -t nat -A POSTROUTING -o $HOST_ETHERNET_INTERFACE -j MASQUERADE
sudo iptables -A FORWARD -i $HOST_ETHERNET_INTERFACE -o $HOST_TAP_INTERFACE -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i $HOST_TAP_INTERFACE -o $HOST_ETHERNET_INTERFACE -j ACCEPT
sudo sysctl -w net.ipv4.ip_forward=1


